(define-key global-map "\C-ca" 'org-agenda)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\M-`" 'other-frame )
(define-key python-mode-map (kbd "C-x a") 'nosetests-all)
(define-key python-mode-map (kbd "C-x m") 'nosetests-module)
(global-set-key (kbd "C-x r v") 'list-register)
;; (global-set-key (kbd "C-x C-b") 'ibuffer)
