(define-key global-map "\C-ca" 'org-agenda)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\M-`" 'other-frame )
(define-key python-mode-map (kbd "C-x a") 'nose2-all)
(define-key python-mode-map (kbd "C-x m") 'nose2-module)
(global-set-key (kbd "C-x r v") 'list-register)
(global-set-key (kbd "C-`") 'next-error)
;; (global-set-key (kbd "C-x C-b") 'ibuffer)
(define-key twittering-mode-map (kbd "C-c C-o") 'osx-browse-url)
(define-key twittering-mode-map (kbd "C-c C-i") 'browse-url-text-emacs)
