(let* ((cygwin-root "c:/cygwin")
       (cygwin-bin (concat cygwin-root "/bin")))
  (setenv "PATH" (concat cygwin-bin ";")
          (getenv "PATH"))
  (setq exec-path (cons cygwin-bin exec-path)))

(require 'cygwin-mount)
(cygwin-mount-activate)
(setq ispell-program-name "aspell")
;    (add-to-list 'exec-path "C:/Program Files (x86)/Aspell/bin/")
;    (setq ispell-program-name "aspell")
;    (setq ispell-personal-dictionary "C:/path/to/your/.ispell")
;    (require 'ispell)
;    (global-set-key (kbd "<f8>") 'ispell-word)
;    (global-set-key (kbd "C-<f8>") 'flyspell-mode)       
